// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:tic_tac_zwo/features/game/online/data/models/german_noun_hive.dart';
import 'package:tic_tac_zwo/features/profile/data/models/user_profile_hive.dart';
import 'package:tic_tac_zwo/features/wortschatz/data/models/saved_noun_hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GermanNounHiveAdapter());
    registerAdapter(SavedNounHiveAdapter());
    registerAdapter(UserProfileHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GermanNounHiveAdapter());
    registerAdapter(SavedNounHiveAdapter());
    registerAdapter(UserProfileHiveAdapter());
  }
}
